id: PBD333838
initial_creation_type: ocr
source_metadata:
  volumes:
    984c968ccf3b46579288302ed824b8c2:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: རིགས་པ་དྲུག་ཅུ་པའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1605
      volume_number: 57
